(** This file is pre-processed by OASIS, which replaces all occurrences
    of environmental variables with their corresponding value.
*)

(********************************************************************************)
(** {1 Public functions and values}                                             *)
(********************************************************************************)

let version = "$(pkg_version)"

